# 데이터 전처리

### 1. 레이블 인코딩

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
items = ['TV','냉장고','전자렌지','선풍기','선풍기','믹서','믹서']

In [8]:
#레이블 인코더 객체 생성
encoder = LabelEncoder()

In [9]:
#데이터를 줘서 상태를 확인. 일종의 학습
encoder.fit(items)

LabelEncoder()

In [10]:
# 인코딩 변환값 반환
labels = encoder.transform(items)
labels

array([0, 1, 4, 3, 3, 2, 2])

In [11]:
# 실전에서는 어떻게 쓰는가
items = ['TV','냉장고','전자렌지','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 3, 3, 2, 2], dtype=int64)

In [12]:
# 코딩 잘하는 경우에
LabelEncoder().fit_transform(items)

array([0, 1, 4, 3, 3, 2, 2], dtype=int64)

### 2.one-hot encoding

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
labels = LabelEncoder().fit_transform(items)

In [18]:
import numpy as np
type(labels)

numpy.ndarray

In [20]:
# 객체생성, 학습 후 변환
oh_encoder = OneHotEncoder()
labels= labels.reshape(-1,1)
oh_encoder.fit(labels)
one_hot = oh_encoder.transform(labels)
one_hot

<7x5 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [22]:
print(one_hot.toarray())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [24]:
# 실전에서는
labels = LabelEncoder().fit_transform(items)
oh_encoder = OneHotEncoder()
one_hot = oh_encoder.fit_transform(labels.reshape(-1,1))
one_hot.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

### 3. standardscaler

In [42]:
from sklearn.datasets import load_iris
iris = load_iris()

In [43]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
iris_std = scaler.fit_transform(iris.data)

In [55]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
iris_std = scaler.fit_transform(iris.data)

In [54]:
import numpy as np
import pandas as pd

In [56]:
df = pd.DataFrame(iris_std, columns= iris.feature)

AttributeError: feature

In [46]:
df.describe()

NameError: name 'df' is not defined

### 4. MinMaxScaler

In [48]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
iris_scaled = mm_scaler.fit_transform(iris.data)

In [49]:
df2 = pd.DataFrame(iris_scaled, columns=iris.feature)

AttributeError: feature